name = "manfredi-calendario"
main = "index.js"
compatibility_date = "2026-04-19"

[vars]
SITE_URL = "https://manfredi-investment-com.pages.dev"

[[kv_namespaces]]
binding = "CALENDARIO_KV"
id = "6d2171ac1fe748f5b30847dd21ffd455"

[triggers]
crons = ["0 9 * * MON"]
