name = "manfredi-calendario"
main = "index.js"
compatibility_date = "2026-04-19"

[vars]
SITE_URL = "https://manfredi-investment-com.pages.dev"

[[kv_namespaces]]
binding = "CALENDARIO_KV"
id = "61d8bfd84a3c4af185c7c8bacbfcb704"

[triggers]
crons = ["0 9 * * MON"]
