name = "manfredi-noticias"
main = "index.js"
compatibility_date = "2026-04-19"

[vars]
SITE_URL = "https://manfredi-investment-com.pages.dev"

[[kv_namespaces]]
binding = "NOTICIAS_KV"
id = "06e9b3baeb9043fbb60b553cc7be38ed"

[triggers]
crons = ["*/30 * * * *"]
